"""add_description_field_to_users_table

Revision ID: 23aa15d3069d
Revises: 1fe741ec39eb
Create Date: 2025-09-20 23:50:09.457864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23aa15d3069d'
down_revision: Union[str, Sequence[str], None] = '1fe741ec39eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add description column to users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove description column from users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('description')
    
    # ### end Alembic commands ###
